[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "readify-booktracker"
version = "0.1.0"
# Add other metadata if needed (description, authors, etc.)

[tool.setuptools.packages.find]
where = ["."]
include = ["readify*"]